### ISSUE TITLE
5.4试了下FF14闪退，不清楚什么问题

### ISSUE THREAD

**Issue by HackFF14** [nyaoouo/FFxivPythonTrigger2#2]
[DEBUG]	[2021-04-30 14:17:52.433|Main]		address found [0x7ff7ee6b3540] [+0x93540] "frame_inject"
[DEBUG]	[2021-04-30 14:17:52.445|Main]		try load plugin "SocketLogger" dynamically
[DEBUG]	[2021-04-30 14:17:52.504|Main]		register plugin [start]: socket logger
[INFO]	[2021-04-30 14:17:52.505|Main]		register plugin [success]: socket logger
[DEBUG]	[2021-04-30 14:17:52.506|Main]		try load plugin "HttpApi" dynamically
[ERROR]	[2021-04-30 14:17:52.525|Main]		error occurred during import module:" HttpApi"
[ERROR]	[2021-04-30 14:17:52.527|Main]		error trace:
Traceback (most recent call last):
  File "C:\Users\WorkStation2\Desktop\FFxivPythonTrigger2-master\FFxivPythonTrigger2-master\FFxivPythonTrigger\FFxivPythonTrigger.py", line 109, in register_module
    module = import_module("plugins.%s" % module)
  File "C:\Users\WorkStation2\AppData\Local\Programs\Python\Python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\Users\WorkStation2\Desktop\FFxivPythonTrigger2-master\FFxivPythonTrigger2-master\plugins\HttpApi.py", line 2, in <module>
    from aiohttp import web
ModuleNotFoundError: No module named 'aiohttp'

[DEBUG]	[2021-04-30 14:17:52.528|Main]		unregister plugin [start]: socket logger
[INFO]	[2021-04-30 14:17:52.858|Main]		unregister plugin [success]: socket logger

**Comment by nyaoouo** [comment]
`ModuleNotFoundError: No module named 'aiohttp'`
华生你有什么头绪么（请pip install aiohttp）
