### ISSUE TITLE
卡在连接端口

### ISSUE THREAD

**Issue by Peekab0o** [nyaoouo/FFxivPythonTrigger2#25]
![image](https://user-images.githubusercontent.com/85273092/165995633-8bc4ad5a-da3d-4232-8687-4f1fd49d1dad.png)
Traceback (most recent call last):
  File "<string>", line 11, in <module>
  File "C:\Users\gm\Desktop\FFxivPythonTrigger2-master\Entrance.py", line 7, in <module>
    from FFxivPythonTrigger import *
  File "C:\Users\gm\Desktop\FFxivPythonTrigger2-master\FFxivPythonTrigger\__init__.py", line 11, in <module>
    from .FFxivPythonTrigger import *
  File "C:\Users\gm\Desktop\FFxivPythonTrigger2-master\FFxivPythonTrigger\FFxivPythonTrigger.py", line 16, in <module>
    from .CheckGitUpdate import get_last_update, check_update
  File "C:\Users\gm\Desktop\FFxivPythonTrigger2-master\FFxivPythonTrigger\CheckGitUpdate.py", line 82, in <module>
    can_check = test_url(domain)
  File "C:\Users\gm\Desktop\FFxivPythonTrigger2-master\FFxivPythonTrigger\CheckGitUpdate.py", line 26, in test_url
    _storage.data['s'] = r.json()['\x49\x50'].encode('utf-8').hex(' ')
  File "C:\Users\gm\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\gm\AppData\Local\Programs\Python\Python39\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\gm\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\gm\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by YuyamaYoru** [comment]
我也是
