### ISSUE TITLE
cannot open it even no logs

### ISSUE THREAD

**Issue by ZYZ-CN** [nyaoouo/FFxivPythonTrigger2#5]
C:\WINDOWS\system32>d:

D:\>cd D:\FF14\FFxivPythonTrigger2-master

D:\FF14\FFxivPythonTrigger2-master>python Injecter.py
start searching for game process...
game process pid: 18160
Traceback (most recent call last):
  File "D:\FF14\FFxivPythonTrigger2-master\Injecter.py", line 40, in <module>
    python_lib = process.module_from_name(python_version).filename
  File "D:\FF14\FFxivPythonTrigger2-master\FFxivPythonTrigger\memory\process.py", line 82, in module_from_name
    for module in modules:
  File "D:\FF14\FFxivPythonTrigger2-master\FFxivPythonTrigger\memory\process.py", line 65, in enum_process_module
    raise exception.WinAPIError(error_code)
FFxivPythonTrigger.memory.exception.WinAPIError: Windows api error, error_code: 5

D:\FF14\FFxivPythonTrigger2-master>

**Comment by nyaoouo** [comment]
copy all the file in `Lib\site-packages\pywin32_system32` to `C:\Windows\System32`

**Comment by nyaoouo** [comment]
this problem cause by unknown problem and i don't know how to deal with it temporarily, so _(:з」∠)_

**Comment by ZYZ-CN** [comment]
Thanks anyway, 555.

**Comment by nyaoouo** [comment]
fixed
