### ISSUE TITLE
注入时卡在waiting for initialization...界面，log如下

### ISSUE THREAD

**Issue by kannadukiise** [nyaoouo/FFxivPythonTrigger2#8]
Traceback (most recent call last):
  File "<string>", line 9, in <module>
  File "<string>", line 7, in <module>
  File "D:\FFxivPythonTrigger2-master (2)\FFxivPythonTrigger2-master\FFxivPythonTrigger\__init__.py", line 11, in <module>
    from .FFxivPythonTrigger import *
  File "D:\FFxivPythonTrigger2-master (2)\FFxivPythonTrigger2-master\FFxivPythonTrigger\FFxivPythonTrigger.py", line 12, in <module>
    from . import AttrContainer, Storage, Logger, FrameInject, Sigs, AddressManager
  File "D:\FFxivPythonTrigger2-master (2)\FFxivPythonTrigger2-master\FFxivPythonTrigger\Storage.py", line 3, in <module>
    from typing import Annotated, Union
ImportError: cannot import name 'Annotated' from 'typing' (C:\Users\kanna\AppData\Local\Programs\Python\Python38\lib\typing.py)

**Comment by nyaoouo** [comment]
请使用Python3.9x64

**Comment by kannadukiise** [comment]
已解决，感谢
